
def rgb2hex(r,g,b):
    return "#{:02x}{:02x}{:02x}".format(r,g,b)

def hex2rgb(value):
	"""Return (red, green, blue) for the color given as #rrggbb."""
	value = value.lstrip('#')
	lv = len(value)
	return tuple(int(value[i:i + lv // 3], 16) for i in range(0, lv, lv // 3))

PALETTES_NAMED = dict(
	{'bright': {'braun': '#9F4800',
				'darkblue': '#023EFF',
	            'grau': '#A3A3A3',
	            'green': '#1AC938',
	            'lightblue': '#00D7FF',
	            'orange': '#FF7C00',
	            'red': '#E8000B',
	            'rose': '#F14CC1',
	            'violet': '#8B2BE2',
	            'yellow': '#FFC400',
	            'cyan': '#41FDFE',
	            'bisque': 'bisque',
	            'turqouise1': 'turquoise2',
	            'snow': 'ghost white',
	            'SpringGreen': 'SpringGreen3',
	            'magente': 'magenta',
	            'darkSeaGreen': 'darkSeaGreen3',
	            'blue': 'blue',
	            },
	 'colorblind': {'braun': '#CA9161',
	                'darkblue': '#0173B2',
	                'grau': '#949494',
	                'green': '#029E73',
	                'lightblue': '#56B4E9',
	                'orange': '#DE8F05',
	                'red': '#D55E00',
	                'rose': '#FBAFE4',
	                'violet': '#CC78BC',
	                'yellow': '#ECE133',
	                'cyan': '#00FFFF',
	                'bisque': 'bisque',
	                'turqouise1': 'medium turquoise',
	                'snow': 'white smoke',
	                'SpringGreen': 'SpringGreen2',
	                'magente': 'magenta2',
	                'darkSeaGreen': 'darkSeaGreen2',
	                'blue': 'blue1',
	                },
	 'deep': {'braun': '#937860',
	          'darkblue': '#4C72B0',
	          'grau': '#8C8C8C',
	          'green': '#55A868',
	          'lightblue': '#64B5CD',
	          'orange': '#DD8452',
	          'red': '#C44E52',
	          'rose': '#DA8BC3',
	          'violet': '#8172B3',
	          'yellow': '#CCB974',
	          'cyan': '#037989',
	          'bisque': 'bisque',
	          'turqouise1': 'turquoise4',
	          'snow': 'gainsboro',
	          'SpringGreen': 'SpringGreen4',
	          'magente': 'magenta4',
	          'darkSeaGreen': 'darkSeaGreen4',
	          'blue': 'blue2',
	          },
	 'pastel': {'braun': '#DEBB9B',
	            'darkblue': '#A1C9F4',
	            'grau': '#CFCFCF',
	            'green': '#8DE5A1',
	            'lightblue': '#B9F2F0',
	            'orange': '#FFB482',
	            'red': '#FF9F9B',
	            'rose': '#FAB0E4',
	            'violet': '#D0BBFF',
	            'yellow': '#FFFEA3',
	            'cyan': '#DCFFFB',
	            'bisque': 'bisque',
	            'turqouise1': 'turquoise1',
	            'snow': 'snow',
	            'SpringGreen': 'PaleGreen1',
	            'magente': 'magenta3',
	            'darkSeaGreen': 'darkSeaGreen1',
	            'blue': 'lightblue2',
	            },
	 }
)
